copy	help-hub.md	all
copy	overview.md	all
copy	whats-new.md	all
copy	removed-deprecated-features.md	admin
copy	intro-admin-guide-sales-insights.md	admin
copy	manage-sample-data.md	admin
copy	configure-assistant.md	admin
copy	create-insight-cards-flow.md	admin
copy	edit-insight-cards.md	admin
copy	optimize-ranking-insight-cards.md	admin
copy	extend-relationship-assistant-card.md	admin
copy	sample-extend-relationship-assistant-card-type.md	admin
copy	Configure productivity intelligence	admin
copy	configure-auto-capture.md	admin
copy	configure-email-engagement.md	admin
copy	configure-notes-analysis.md	admin
copy	Configure relationship insights	admin
copy	configure-relationship-analytics.md	admin
copy	configure-talking-points.md	admin
copy	configure-who-knows-whom.md	admin
copy	Configure predictive models	admin
copy	configure-predictive-lead-scoring.md	admin
copy	configure-predictive-opportunity-scoring.md	admin
copy	configure-premium-forecasting.md	admin
copy	view-prediction-model-status.md	admin
copy	manage-snapshots-forecast.md	admin
copy	Configure sales accelerator	admin
copy	enable-configure-sales-accelerator.md	admin
copy	create-manage-sequences.md	admin
copy	create-and-activate-a-sequence.md	admin
copy	adaptive-sequence.md	admin
copy	linkedin-activities-sequence.md	admin
copy	connect-a-sequence-to-records.md	admin
copy	view-sequence-details-connected-records.md	admin
copy	clone-a-sequence.md	admin
copy	edit-a-sequence.md	admin
copy	edit-active-sequence.md	admin
copy	delete-a-sequence.md	admin
copy	manage-segments.md	admin
copy	create-and-activate-a-segment.md	admin
copy	connect-a-segment-to-sequence.md	admin
copy	edit-a-segment.md	admin
copy	delete-deactivate-a-segment.md	admin
copy	create-manage-assignment-rules.md	admin
copy	create-and-activate-assignment-rule.md	admin
copy	edit-assignment-rule.md	admin
copy	delete-deactivate-assignment-rule.md	admin
copy	manage-sales-teams.md	admin
copy	manage-seller-attributes.md	admin
copy	integrate-sample-softphone.md	admin
copy	add-upnext-widget-form.md	admin
copy	Configure conversation intelligence	admin
copy	prereq-sales-insights-app.md	admin
copy	fre-setup-sales-insight-app.md	admin
copy	configure-sales-team-level-settings.md	admin
copy	configure-conversation-intelligence-call-data.md	admin
copy	configure-view-your-team-page.md	admin
copy	configure-keywords-competitors.md	admin
copy	connect-dynamics365-sales-environment.md	admin
copy	data-retention-deletion-policy.md	admin
copy	enable-preview-features-sales-insights-app.md	admin
copy	embedded-intelligence-gdpr.md	admin
copy	view-export-KPI-data-gdpr.md	admin
copy	retrieve-insights-data-msdyn-RetrieveTypeValuesFromDCI.md	admin
copy	uninstall-sales-insights.md	Seller
copy	assistant.md	Seller
copy	action-cards-reference.md	Seller
copy	auto-capture.md	Seller
copy	free-auto-capture.md	Seller
copy	premium-auto-capture.md	Seller
copy	email-engagement.md	Seller
copy	notes-analysis.md	Seller
copy	relationship-analytics.md	Seller
copy	talking-points.md	Seller
copy	who-knows-whom.md	Seller
copy	work-predictive-lead-scoring.md	Seller
copy	work-predictive-opportunity-scoring.md	Seller
copy	analyze-revenue-outcome-using-predictive-forecasting.md	Seller
copy	understand-forecast-projection-through-trend-chart.md	Seller
copy	analyze-deals-flow-between-snapshots.md	Seller
copy	view-snapshots.md	Seller
copy	sales-accelerator-intro.md	Seller
copy	prioritize-sales-pipeline-through-work-list.md	Seller
copy	connect-with-customers.md	Seller
copy	work-with-linkedin-activities.md	Seller
copy	personalize-sales-accelerator.md	Seller
copy	dynamics365-sales-insights-app.md	Seller
copy	dynamics365-sales-insights-app-home-page.md	Seller
copy	conversation-intelligence-team-overview.md	Seller
copy	conversation-intelligence-seller-details.md	Seller
copy	view-and-understand-call-summary.md	Seller
copy	monitor-call-insight-processing.md	Seller
copy	developer/msdyn-ConnectSequence-action.md	Seller
copy	entity-reference.md	Seller
copy	developer/msdyn_predictivescore.md	Seller
copy	developer/msdyn_predictivemodelscore.md	Seller
copy	troubleshooting-sp.md	Seller
copy	faqs-sales-insights.md	Seller
copy	privacy-notice.md	all
