copy	help-hub.md	All
copy	sign-up-for-sales-trial.md	All
copy	sales-trial-faq.md	All
copy	sales-previews-in-trial.md	All
copy	set-up-dynamics-365-sales.md	Admin
copy	overview.md	All
copy	whats-new.md	All
copy	deprecations-sales.md	All
copy	connect-share-feedback.md	All
copy	admin-guide.md	Admin
copy	admin-settings-overview.md	Admin
copy	security-roles-for-sales.md	Admin
copy	system-settings-sales-tab.md	Admin
copy	enable-pdf-generation-quote.md	Admin
copy	set-up-enhanced-email.md	Admin
copy	deal-manager-overview.md	Admin
copy	enable-deal-manager-preview.md	Admin
copy	grant-access-deal-manager.md	Admin
copy	customize-deal-manager.md 	Admin
copy	enable-opportunity-close-customization.md	Admin
copy	customize-opportunity-close-experience.md	Admin
copy	define-lead-qualification-experience.md	Admin
copy	make-price-list-optional.md	Admin
copy	retain-business-card-image-after-scanning.md	Admin
copy	customize-business-card-scan-control.md	Admin
copy	add-kanban-control.md	Admin
copy	set-up-product-catalog-walkthrough.md	Admin
copy	configure-product-catalog-settings.md	Admin
copy	create-product-sales.md	Admin
copy	create-product-family.md	Admin
copy	create-product-bundles-sell-multiple-items-together.md	Admin
copy	pricing-product-bundles.md	Admin
copy	change-product-parent.md	Admin
copy	publish-product-bundle-make-available-selling.md	Admin
copy	create-price-lists-price-list-items-define-pricing-products.md	Admin
copy	decimal-precision-currency-pricing.md	Admin
copy	create-unit-group-add-units-that-group.md	Admin
copy	set-up-discount-list.md	Admin
copy	define-related-products-increase-chances-sales.md	Admin
copy	translate-product-names-properties-into-multiple-languages.md	Admin
copy	use-properties-describe-product.md	Admin
copy	revise-product.md	Admin
copy	clone-product.md	Admin
copy	retire-product.md	Admin
copy	delete-family-product-bundle.md	Admin
copy	editable-product-grid-forms.md	Admin
copy	enable-enhanced-add-product-experience.md	Admin
copy	customize-add-products-dialog-box.md	Admin
copy	goals-overview.md	Admin
copy	create-edit-goal-sales.md	Admin
copy	create-edit-goal-metric.md	Admin
copy	create-edit-goal-rollup-query-sales.md	Admin
copy	configure-forecast.md	Admin
copy	select-template-forecast.md	Admin
copy	define-general-properties-scheduling-forecast.md	Admin
copy	provide-permissions-forecast.md	Admin
copy	choose-layout-and-columns-forecast.md	Admin
copy	add-additional-filters.md	Admin
copy	configure-manage-drill-downs.md	Admin
copy	forecast-configure-advanced-settings.md	Admin
copy	activate-upload-simple-columns-data-forecast.md	Admin
copy	deactivate-delete-forecast.md	Admin
copy	clone-forecast.md	Admin
copy	forecast-different-data-types.md	Admin
copy	configure-forecast-using-custom-rollup-entity.md	Admin
copy	capture-forecast-category-opportunity.md	Admin
copy	add-forecast-site-map.md	Admin
copy	sales-accelerator-assignment-rules.md	Admin
copy	manage-segments.md	Admin
copy	create-and-activate-a-segment.md	Admin
copy	edit-a-segment.md	Admin
copy	delete-deactivate-a-segment.md	Admin
copy	create-manage-assignment-rules.md	Admin
copy	create-and-activate-assignment-rule.md	Admin
copy	edit-assignment-rule.md	Admin
copy	delete-deactivate-assignment-rule.md	Admin
copy	manage-sales-teams.md	Admin
copy	manage-seller-attributes.md 	Admin
copy	define-playbook-categories.md	Admin
copy	manage-playbook-templates.md	Admin
copy	associate-documents-playbook-activities.md	Admin
copy	introduction-sales-template-apps.md	Admin
copy	configure-sales-template-apps.md	Admin
copy	customize-template-apps.md	Admin
copy	install-lsi-solution.md	Admin
copy	install-zoominfo-app.md	Admin
copy	configure-export-preferences-zoominfo.md	Admin
copy	match-fields-between-dynamics365-zoominfo.md	Admin
copy	customize-zoominfo-app.md 	Admin
copy	configure-microsoft-teams-dialer.md	Admin
copy	dynamics-365-sales-gdpr.md	Admin
copy	upgrade-sales-professional-sales-enterprise.md	Admin
copy	move-sales-enterprise-sales-professional.md	Admin
copy	user-guide.md	Seller
copy	user-guide-learn-basics.md	Seller
copy	dashboards.md	Seller
copy	sales-pipeline-chart.md	Seller
copy	enhanced-email.md	Seller
copy	create-quote-pdf.md	Seller
copy	print-records.md	Seller
copy	manage-activities.md	Seller
copy	activity-kanban-view.md	Seller
copy	../customerengagement/on-premises/basics/accounts-contacts.md	Seller
copy	understand-lsi-accounts-form.md	Seller
copy	live-org-chart.md	Seller
copy	scan-business-cards.md	Seller
copy	nurture-sales-from-lead-order-sales.md	Seller
copy	create-edit-lead-sales.md	Seller
copy	qualify-lead-convert-opportunity-sales.md	Seller
copy	create-edit-opportunity-sales.md	Seller
copy	deal-manager-seller-overview.md	Seller
copy	access-deal-manager.md	Seller
copy	personalize-deal-manager.md	Seller
copy	opportunity-kanban-view.md	Seller
copy	re-open-lead-sales.md	Seller
copy	add-products-opportunity.md	Seller
copy	add-products-enhanced-experience.md	Seller
copy	price-calculation-opportunity-quote-order-invoice-records.md	Seller
copy	stakeholders-sales-team-members.md	Seller
copy	recalculate-opportunity.md	Seller
copy	close-opportunity-won-lost-sales.md	Seller
copy	collaborate-using-sharepoint-sales.md	Seller
copy	create-edit-competitor-record-sales.md	Seller
copy	create-sales-literature.md	Seller
copy	use-zoominfo-app-data.md	Seller
copy	sales-transactions.md	Seller
copy	lock-unlock-price-order-invoice.md	Seller
copy	create-edit-quote-sales.md	Seller
copy	close-quote.md	Seller
copy	create-edit-order-sales.md	Seller
copy	create-edit-invoice-sales.md	Seller
copy	add-product-quote-order-invoice.md	Seller
copy	add-products-qoi-enhanced.md	Seller
copy	project-accurate-revenue-sales-forecasting.md	Seller
copy	view-forecasts.md	Seller
copy	view-understand-data-through-drill-down.md	Seller
copy	view-and-manage-underlying-opportunities.md	Seller
copy	adjust-values-in-forecast.md	Seller
copy	keep-forecast-data-up-to-date.md	Seller
copy	enforce-best-practices-playbooks.md	Seller
copy	launch-playbook.md	Seller
copy	mark-playbook-completed.md	Seller
copy	track-playbook-activities.md	Seller
copy	configure-your-work-availability.md	Seller
copy	get-started-app-marketing-sales.md	Seller
copy	create-marketing-list-using-app-marketing-sales.md	Seller
copy	create-quick-campaign-using-app-marketing-sales.md	Seller
copy	add-marketing-list-sales-literature-product-campaign-using-app-marketing-sales.md	Seller
copy	create-edit-campaign-using-app-marketing-sales.md	Seller
copy	add-activity-campaign-using-app-marketing-sales.md	Seller
copy	track-marketing-campaign-response-using-app-marketing-sales.md	Seller
copy	use-sales-hub-on-mobile-app.md	Seller
copy	use-sales-hub-on-dynamics-365-mobile.md	Seller
copy	troubleshooting.md	Seller
copy	ts-leads.md	Seller
copy	ts-opportunities.md	Seller
copy	ts-orders.md	Seller
copy	ts-products.md	Seller
copy	ts-oqoi.md	Seller
copy	ts-currency-pricelist.md	Seller
copy	ts-views.md	Seller
copy	ts-forecasts.md	Seller
copy	ts-unified-interface.md	Seller
copy	ts-sales-pipeline.md	Seller
copy	ts-inapp-marketing.md	Seller
copy	ts-email.md	Seller
copy	faqs-sales.md	Seller
copy	sample-softphone-integration.md	Seller
copy	../sales-professional/help-hub.md	All
copy	sales-team-member.md	All